name: Make PDFs

on: push

jobs:
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: invoke Pandoc via Docker
        run: ./make-pdf.sh
      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf